feat: add json schema
joellord/cli-slides pull request #2
Opened 2021-04-30 14:34 UTC by Favna

I autogenerated this with https://www.liquid-technologies.com/online-json-to-schema-converter based on `demo.json`, and then manually adjusted it a bit using the README as a reference. It's probably not perfect but it helps anyway.

Editors such as VSCode can read the file and give code completion based on the schema when given like so:

```json
{
    "$schema": "https://raw.githubusercontent.com/joellord/cli-slides/master/assets/json-schema.json"
}
```
(or `https://raw.githubusercontent.com/Favna/cli-slides/feat/add-json-schema/assets/json-schema.json` if you want to test it)

2021-04-30 16:37 UTC, joellord commented
This look good and I really like the idea of having a $schema for the JSON slides. However, the way it is built right now, it's expecting all the slide types in the format specified in the proposed schema. 
I am not familiar with json-schema, but my understanding is that it might need a schema for each slide type. Then "items" would "contain" "anyOf" the new types.
I will look into this soon-ish. Feel free to comment if I have a bad understanding of how it works.

2021-05-15 15:04 UTC, Favna commented
@joellord it took me quite a while to get around it but it was worth the wait I'd say.

The schema is completely fixed now. As soon as a `type` is provided in the slides, all the other properties, descriptions and other schema keys are resolved like magic. 

I also took the liberty of rewriting big chunks of the README, in particular a bunch of Markdown formatting (lists, syntax highlighting, etc). I also improved the "header" part a bit to be more catchy and for my own slides I wrote a simple JavaScript file to start the presentation so I can use `node /path/to/file.mjs`, figured I'd add a section about that as well.

Lastly I added a LICENSE.md for the ISC license that's on this project and put the year 2019 in there as that's when you first committed to this repo.

2021-05-15 17:16 UTC, kyranet requested changes

2021-05-15 17:16 UTC, kyranet commented on typings/presentation.d.ts
> +
```suggestion
```

2021-05-15 21:04 UTC, Nytelife26 requested changes
Just grammar nitpicks, as per usual.

2021-05-15 21:04 UTC, lveneris commented on README.md
> +If you would prefer to start your presentation through JavaScript, for example if you want to be able to call `node start-slides.js` then you can create a script like this:
```suggestion
If you would prefer to start your presentation through JavaScript, for example if you want to be able to call `node start-slides.js`, then you can create a script like this:
```

2021-05-15 21:04 UTC, lveneris commented on README.md
> +CLI Slides is a framework to build slide decks that will run in the terminal. This application will use a JSON file to generate a full slide deck. You can use many of the different templates for the
```suggestion
CLI Slides is a framework to build slide decks that will run in the terminal. This application will use a JSON file to generate a full slide deck. You can use many of the different templates for the slides - or, if you feel adventurous, you can even create your own.
```

2021-05-15 21:04 UTC, lveneris commented on README.md
>  Once you start the presentation tool, it will support hot reloading of you slide deck. This means you can open your presentation, change the JSON file and you should immediately see the changes in yo
```suggestion
Once you start the presentation tool, it comes with hot reloading for your slide deck, so you can change the JSON file and preview your changes on the fly.
```

2021-05-15 21:04 UTC, lveneris commented on README.md
> +After infalling `cli-slides` you can start your slidedeck by passing it the slidedeck JSON file as first argument:
```suggestion
After installing `cli-slides` you can start your slidedeck by passing it the slidedeck JSON file as the first argument, like so:
```

2021-05-15 21:04 UTC, lveneris commented on README.md
> +Optionally you can also provide a second argument to directly jump to the slide with that index (1-based):
```suggestion
Optionally, you can also provide a second argument to directly jump to the slide with the specified index (starting from 1):
```

2021-05-15 21:04 UTC, lveneris commented on README.md
> +A Json schema is available in [./assets/json-schema.json](/assets/json-schema.json). You can use it in your JSON like so:
```suggestion
A JSON schema is available at [`assets/json-schema.json`](assets/json-schema.json). You can use it in your JSON like so:
```

2021-05-15 21:04 UTC, lveneris commented on README.md
> +You can specify what to display at the top of the slides, in the center by setting the `frame.top.center` property. CLI-slides will try to find a matching property in the deck definition or will disp
```suggestion
You can specify content to display centered at the top with the `frame.top.center` property. First, `cli-slides` will attempt to find a property matching the value you set, but if one doesn't exist, it will display the specified text.
```

2021-05-15 21:04 UTC, lveneris commented on README.md
> +- `code`: The code snippet to be displayed, will be enclosed in a box. Use an array to display multiple lines of code.
```suggestion
- `code`: The code snippet to be displayed inside of a code block. Use an array to display multiple lines of code.
```

2021-05-15 21:04 UTC, lveneris commented on README.md
> +- `multistep` (optional): boolean.
```suggestion
- `multistep` (optional): A boolean to toggle multistep mode.
```

2021-05-15 21:04 UTC, lveneris commented on README.md
> +- `multistepType` (optional): "line" or "highlight". Will display one line at a time or one highlighted item at a time.
```suggestion
- `multistepType` (optional): This can take two values; "line", or "highlight". "line" displays one line at a time, "highlight" displays one highlighted item at a time.
```

2021-05-15 21:04 UTC, lveneris commented on README.md
>  Used to display some text on the left side and some ASCII art on the right side. You're on your own to draw that diagram though.
```suggestion
Used to display some text on the left side and some ASCII art on the right side. Drawing the diagram is your responsibility, though - there are none provided with `cli-slides`.
```

2021-05-15 21:04 UTC, lveneris commented on README.md
> +- `diagram`: An array of strings to be displayed on the right side.
```suggestion
- `diagram`: An array of strings to be displayed as lines of ASCII art on the right of the slide.
```

2021-05-15 21:04 UTC, lveneris commented on README.md
>  A list of items. Items can be displayed at once or one at a time.
```suggestion
A list of items. Items can either be displayed one at a time, or all at once.
```

2021-05-15 21:04 UTC, lveneris commented on README.md
> +- `text`: Some text to be displayed. Text will be centred and wraps automatically. Supports multiple lines with the \n character
```suggestion
- `text`: Some text to be displayed. Text will be centred and wraps automatically. Supports multiple lines with a newline escape (`\n`).
```

2021-05-15 21:04 UTC, lveneris commented on README.md
> +  - `me-oh-no`: Same as me with closed eyes and open mouth
```suggestion
  - `me-oh-no`: The same as `me`, but with closed eyes and open mouth
```

2021-05-15 21:04 UTC, lveneris commented on README.md
> +- `text`: Text to be displayed in a bubble
```suggestion
- `text`: Text to be displayed next to the character in a speech bubble
```

2021-05-15 21:04 UTC, lveneris commented on README.md
>  The famous terminal inside the terminal!
```suggestion
The famous terminal-in-a-terminal! ~~(obligatory inception joke goes here)~~
```

2021-05-15 21:04 UTC, lveneris commented on README.md
>  Just a title slide. Can be used for section separator.
```suggestion
Just a title slide, typically used as a section separator.
```

2021-05-15 21:04 UTC, Nytelife26 commented on assets/json-schema.json
> +          "description": "Whether this slide should show it's content in multiple steps, advancing a step every time the enter key is pressed."
```suggestion
          "description": "Whether this slide should show its content in multiple steps, advancing a step every time the enter key is pressed."
```

2021-05-15 21:04 UTC, Nytelife26 commented on assets/json-schema.json
> +      "description": "A slide template to display code. Code be be displayed as a whole, line by line, or one highlighted section at a time.",
```suggestion
      "description": "A slide template to display code. Code can be displayed as a whole, line by line, or one highlighted section at a time.",
```

2021-05-15 21:04 UTC, Nytelife26 commented on assets/json-schema.json
> +          "description": "The code snippet to be displayed, will be enclosed in a box. Use an array to display multiple lines of code.",
```suggestion
          "description": "The code snippet to be displayed in a code block. Use an array to display multiple lines of code.",
```

2021-05-15 21:04 UTC, Nytelife26 commented on assets/json-schema.json
> +      "description": "Used to display some text on the left side and some ASCII art on the right side. You're on your own to draw that diagram though.",
```suggestion
      "description": "Used to display some text on the left side and some ASCII art on the right side. The ASCII art is down to you though, there are none provided by `cli-slides`.",
```

2021-05-15 21:04 UTC, Nytelife26 commented on assets/json-schema.json
> +          "description": "Some text to be displayed. Text will be centered and wraps automatically. Supports multiple lines with the \n character"
```suggestion
          "description": "Some text to be displayed. Text will be centered and wraps automatically. Supports multiple lines with a newline escape (\n).
```

2021-05-15 21:04 UTC, Nytelife26 commented on assets/json-schema.json
> +          "description": "- over-cubbie: Someone looking over a wall\n- me: A man smiling\n- me-oh-no: Same as me, with closed eyes and open mouth\n- silly-face: A face with confused look\n- scream:
```suggestion
          "description": "- over-cubbie: Someone looking over a wall\n- me: A man smiling\n- me-oh-no: Same as me, with closed eyes and an open mouth\n- silly-face: A face with confused look\n- scream: The scream emoji converted to ASCII art"
```

2021-05-15 21:04 UTC, Nytelife26 commented on assets/json-schema.json
> +      "title": "The famous terminal inside the terminal!",
```suggestion
      "title": "The famous terminal-in-a-terminal!",
```

2021-05-15 21:04 UTC, Nytelife26 commented on assets/json-schema.json
> +      "description": "Just a title slide. Can be used for section separator.",
```suggestion
      "description": "Just a title slide, typically used as a section separator.",
```

2021-05-15 21:10 UTC, Favna commented
This is why having friends and talking about PRs is great. Thanks for the grammar/format checking @Nytelife26 and @kyranet <3

2021-05-17 12:08 UTC, joellord commented
Thanks for the contribution!

2021-05-17 12:08 UTC, merged

2021-05-17 19:01 UTC, Favna commented
@joellord Just 1 request - could you also make a release to NPM, so the typings and ESM export are available there? I have a presentation planned soon-ish for my colleagues and what the slides I have prepped so far are in fact using this lib 😉 

(p.s. some of the info is what I learned at iJS 😛)

2021-05-17 19:25 UTC, joellord commented
Done! I had to adjust the version numbers so the official release is 1.2.0 now. 

Let me know on Twitter (https://twitter.com/joel__lord) how the presentation goes! 🎉